### ISSUE TITLE
Failed to connect to server, rc: -1. Error: 'Connection refused' (errno: 111)

### ISSUE THREAD

**Issue by jediofgever** [gavanderhoorn/fanuc_driver_exp#20]
Hello , 
when i try to execute the plan I did with Move-it on real robot, My program stuck at the error given in the title , does anyone met this problem ? on real robot 
I can successfully ping to my robot IP 
any help is appreciated , 
Thank you

**Comment by gavanderhoorn** [comment]
First thing to check: are you (attempting to) use a wireless connection with the robot? If there is any wireless segment between you and the robot (ie: robot cabled with switch/router, but laptop->router is wireless), that will not work reliably.

If that's not it: please provide *much* more information. Versions of components involved (both hw and software), network topology, how you start things up (ie: which `.launch` files, in which order), how you start the programs on the Fanuc controller and last but not least: a wireshark capture of network traffic between the ROS PC and the controller while you experience the problem.

**Comment by jediofgever** [comment]
Thank you for your amazingly fast reply, it turns out to be something related to teach pendant, I am very new to the this robots hardware, now it is solved and I can sucessfully plan and execute on real robot
again thank you :)

**Comment by gavanderhoorn** [comment]
Good to hear that you got things to work.

>  I am very new to the this robots hardware,

let me play "grandpa" here a bit and insist/suggest/require that you get some training. These robots can be highly dangerous if used in an unusual way, especially when using external control (like ROS, but there are other methods as well).

For your own safety, but perhaps also to avoid running into the kind of issues you reported in your OP, you may want to look into getting at least a basic training with Fanuc robots.

`</end_of_grandpa_mode>`

**Comment by jediofgever** [comment]
You are absolutely right on that, I have worked on this field but haven't getting enough experience on the hardware and in the project we do have people with experience on fanuc robots, you are right I should get a training session for this specific robot.
I deeply thank you for your concern and guidance, really appreciate it🙏
And just as a side note; since I am working with the very same robot, for this repository are there open fields waiting for  conribution ? I would be much happy if there is a field that I am capable to contribute

**Comment by gavanderhoorn** [comment]
>  for this repository are there open fields waiting for conribution ?

That depends a bit on what skills you have: are you proficient in Karel & TP?

**Comment by jediofgever** [comment]
oh unfortunately not that proficient in Karel & TP, what I actually meant was contribution to general development related ROS-fanuc software, I am proficient in C++, ROS, Gazebo and maybe a little python

**Comment by gavanderhoorn** [comment]
The main issue tracker would be here: [ros-industrial/fanuc/issues](https://github.com/ros-industrial/fanuc/issues). One outstanding issue that may be something to take a look at would be ros-industrial/fanuc#245.

You are also very much welcome to pick any of the others, although driver development itself has somewhat stopped due to *Stream Motion* becoming available.

That will not work for older controllers, or controllers without the option though, so development of an improved driver for R-30iB and older would still be of interest as well.
