### ISSUE TITLE
Migrate to ros-industrial/fanuc

### ISSUE THREAD

**Issue by gavanderhoorn** [gavanderhoorn/fanuc_driver_exp#5]
Issue tracking development in order to make `fanuc_driver_exp` the preferred ROS-Industrial driver for Fanuc robots.

 - [ ] fix traj_stop behaviour as much as possible (#3, but this depends a bit on `ros-industrial/industrial_core` (or `fanuc_driver` needs to be extended to implement the required msg support, like `motoman_driver`))
 - [ ] improve error handling in traj pt buffer (#4)
 - [ ] update tutorials / documentation (on ROS wiki, or use Sphinx docs)

**Comment by gavanderhoorn** [comment]
Migrating to this newer driver would address/connect to the following issues: ros-industrial/fanuc#1, ros-industrial/fanuc#9, ros-industrial/fanuc#19, ros-industrial/fanuc#22, ros-industrial/fanuc#92, ros-industrial/fanuc#93 and ros-industrial/fanuc#106 (linear axes).

**Comment by gavanderhoorn** [comment]
As interest in integrating this into `ros-industial/fanuc` has decreased (ros-industrial/ros_industrial_issues#49) I'm going to close this.

With better interfaces around the corner, I'm not sure how much longer we'll (I'll)  support `fanuc_driver` and `fanuc_driver_exp`.

**Comment by joao-pm-santos96** [comment]
What do you mean by this? What better interfaces?
> With better interfaces around the corner, I'm not sure how much longer we'll (I'll) support `fanuc_driver` and `fanuc_driver_exp`.

**Comment by gavanderhoorn** [comment]
> What better interfaces?

Hard real-time, external position control (ie: `J519`).

Using Karel+TP is never going to give the same amount of control over how the controller executes the motion.
